althea-net/open5gs

README.md, lib/core/ogs-log.c, lib/core/ogs-log.h, src/hss/hss-init.c, src/mme/mme-context.c, src/mme/mme-init.c, src/pcrf/pcrf-init.c, src/sgwc/init.c, src/sgwu/init.c, src/smf/init.c, src/upf/init.c
This branch will track the current version we're using for KeyLTE builds/releases in the wild. I'm trying to create a sane branch history wherein it shows where we forked from open5gs/open5gs (Release 2.3.3) and what improvements we've made (export metrics/monitoring) in a sane/clean way.
=> setting up a release branch

lib/pfcp/context.c, lib/pfcp/context.h, lib/pfcp/path.h
In our deployment architecture the SGWC is setup with a large number of TAC IDs for UPSes that may or may not be online. As a result of this, the SGWC sends a large number of PFCP Associate Session Requests... that timeout... over and over and over. This option allows us to put the SGWC into a "listening" mode wherein the SGWU must reach out to the SGWC.
=> [pfcp] add send_asr config option

src/sgwc/sxa-handler.c, src/sgwu/pfcp-sm.c, src/sgwu/sxa-handler.c, src/smf/n4-handler.c, src/upf/n4-handler.c, src/upf/pfcp-sm.c
Straightforward PR that makes PFCP more idempotent with respect to session deletions.
Right now, if the SMF (or SGWC) sends a Session-Deletion-Request for a session that the UPF (or SGWU) already does not have, the UPF will return an error (OGS_PFCP_CAUSE_SESSION_CONTEXT_NOT_FOUND). The SMF will ignore this error message and continue to send Session-Deletion-Request messages and potentially GTPv2 error messages depending on the exact codepath. As a side-note, this situation (being out of sync) can happen if the UPF crashes or intermittently loses connectivity with the SMF.
With this PR, the UPF returns the same error message and log entries, but the SMF handles this particular error (session not found) the same way as if the request had succeeded, since the state is the same either way. …
=> make PFCP Session-Delete-Request idempotent

lib/nas/5gs/types.h, lib/nas/eps/types.h
In commit 6cd832199d5c2619c9b295d148b01a6164091680 we increased the max number of TAIs (defined in macro OGS_MAX_NUM_OF_TAI) from 16 to 256. However, the "num" field used to search/lookup/index the number of TACs for a given TAI is only 5bits long, and therefore overflows (with very unhelpful error-messages) if you have n > 32 TACs no matter what the value of OGS_MAX_NUM_OF_TAI is.
For our purposes 8 bits would suffice, but the true solution is choosing a value large enough that sizeof(num) will always be < OGS_MAX_NUM_OF_TAI. I am using uint16_t because the TAC field itself is only 16 bits, so we should never see more than 2^16 different TACs for a given PLMN.
=> increase the bitsize of the "num" field that indexes TACs for a given TAI

lib/pfcp/xact.c
The `if (ogs_pfcp_sendto(xact->node, pkbuf) != OGS_OK)` line will executed if the sending node encounters any sort of socket/sendto errors. In this case, jumping to `out` and calling `pfcp_xact_delete()` without any new timers set will essentially "deadlock" this side of the connection into radio silence. If we just log the error and return, the error is picked up and handled by the calling function, the next timer gets set, and code proceeds as normal.
Socket errors are uncommon over localhost but this problem is actually big for our deployment context because our routers will often hit very temporary/intermittent socket errors if the VPN they're using to communicate stumbles or isn't yet online.
=> [pfcp] response_timeout should not call ogs_pfcp_xact_delete

lib/pfcp/handler.c, src/sgwc/pfcp-sm.c, src/smf/pfcp-sm.c
This PR adds some unorthodox-yet-still-3gpp-compliant behavior to PFCP. The context for this PR is that in our deployment model, the user plane PFCP components (sgw-u and upf) are located on a separate machine from the control plane components (sgw-c and smf). As such, the code needs to be hardened against intermittent connectivity and/or message drops, but also against the complete failure of one or more components. The modifications in this PR address a number of out-of-sync situations we've seen in the wild, and explicitly make the assumption that the cloud CPS entities "control" the UPS entities, and are therefore authoritatively correct. The changes to the code are as follows:
- Previous PRs ensured that individual PFCP operations (add, update, remove) are idempotent from the …
=> [pfcp] make user-plane pfcp nodes stateless

lib/core/ogs-time.c
the open5gs time structure (ogs_time_t) is a 64bit int that counts in microseconds. The ogs_get_monotonic_time() function receives a system-specific timestruct (measured in seconds and nanoseconds) and converts to 64bit microseconds. On 32bit systems, the line `ts.tv_sec * 1000000UL` will do the math as 32bits before casting the whole number to 64bits; this 
effectively creates an overflow that deadlocks the system every 71minutes. The solution is to explicitly cast `ts.tv_sec` to 64bits before the math.
=> [core] fix timer overflow on 32bit systems

src/sgwc/s11-handler.c
We see these messages on occasion after a successful attach if the eNB's first data-plane message beats the final session modification message from the SGWC->SGWU. It is essentially a NOOP since the session estab message is already in-flight, so logging it as "GTP Failed" creates a red herring.
=> do not throw a warning/error on OGS_GTP2_CAUSE_UE_ALREADY_RE_ATTACHED

lib/core/ogs-pool.h, src/smf/context.c
`smf_sess_remove` usually should not be called more than once for a given smf_sess_t structure, but in some obscure codepaths (due to sessions added/removed via different APNs) it is intentionally called again on a smf_sess_t. In these cases the code currently segfaults due to double-frees that are addressed in this PR.
=> Need to make smf_sess_remove idempotent

src/sgwc/context.c
Problem context is similar to #18 but for sgwc instead of smf. Again, it is *very* unlikely that this codepath gets called twice for the same sgwc_sess_t, but the code does acknowledge that it can happen. Either way, by checking for double-frees we effectively make this operation idempotent, which is always a plus.
=> Need to make sgwc_sess_remove idempotent

src/sgwc/pfcp-sm.c
Part of idempotent session_delete means we changed the plumbing into sgwc_sxa_handle_session_deletion_response to handle cases where there's no sess, or we find it a different way (based of of xact). It follows that for other error messages, sess might not exist, so we need to avoid a segfault.
=> [sgwc] need check for sess before calling sgwc_sxa_handle_session_deletion_response

src/sgwc/pfcp-path.c
I have seen this cause a crash twice in sgwc_pfcp_send_bearer_to_modify_list. Unsure the exact logic/situation that leads to this codepath but we should handle gracefully.
=> [sgwc] do not send empty bearer_to_modify_list

.github/workflows/meson-ci.yml
It is unclear why exactly this is the case, but mongodb installation recently started failing for the osx build in this meson CI script. Removing this line (which has already been done upstream in open5gs/open5gs:7231daf) fixes the issue and gets the OSX build/tests to succeed.
=> remove mongodb install from osx script

lib/app/ogs-context.c, lib/core/ogs-3gpp-types.h
This PR rearchitects OGS_MAX_NUM_OF_TAI and OGS_MAX_NUM_OF_SERVED_TAI to resolve #27
=> re-architect TAI/TAC maximums

lib/pfcp/context.c, lib/pfcp/context.h, lib/pfcp/handler.c, src/sgwc/context.c, src/sgwc/pfcp-path.c, src/sgwc/pfcp-path.h, src/sgwc/pfcp-sm.c, src/sgwu/context.c, src/sgwu/sxa-handler.c, src/smf/context.c, src/smf/pfcp-path.c, src/smf/pfcp-path.h, src/smf/pfcp-sm.c, src/upf/context.c, src/upf/n4-handler.c
cf47336 (#11) introduced some complicated and major regressions due to a fundamental misunderstanding of the role of ogs_list structure. The goal of the previous PRs was to keep track of the current pfcp sessions each pfcp node has, so that they can easily be re-established after a PFCP disconnection (main logic: after a crash, send session-set-delete to the node followed by session-establishment-request for each active session).
However, ogs_list is also used for memory management, so an entity (i.e. pfcp_sess_t) can only belong to one list at any given time, and as previously written, pfcp_sess_t was "owned" by its corresponding ue_t. Hence, cf47336 caused a wide range of undefined behavior by adding the same node to multiple lists upon establishment, and freeing it from all lists upon …
=> need to remove pfcp->sess_list

src/mme/mme-context.c, src/smf/s5c-handler.c
Each and every line of code in this PR induces at least one test-failure or crash. Some fixes are obvious (e.g. "num_enbs" file needs "mme/" in front of it) but others are not quite clear yet. Commenting them out for now to get us to a stable/working dev branch; will investigate and push fixes when we have more time.
=> stats functions are creating segfaults/crashes

lib/core/ogs-log.c, lib/core/ogs-log.h, src/mme/esm-handler.c, src/mme/mme-context.c, src/mme/mme-context.h, src/mme/mme-init.c, src/mme/mme-sm.c, src/mme/s1ap-handler.c, src/sgwc/context.c, src/smf/context.c, src/smf/context.h, src/smf/s5c-handler.c
The stats/logging functions actually needed more thought/work than initially realized. ca6654c reverted the changes for purposes of stability, and now this commit adds them back in, this time thoroughly tested and crash-proof.
=> Improve stats-tracking for CPS

src/sgwc/pfcp-sm.c, src/sgwu/pfcp-sm.c, src/smf/pfcp-sm.c, src/upf/pfcp-sm.c
Self-explanatory, will help a lot in the CPS (since we have a large number of PFCP assoc/de-assoc events).
=> add address/port to PFCP association log messages

src/sgwc/context.h, src/sgwc/pfcp-sm.c, src/sgwc/sxa-handler.c, src/sgwc/sxa-handler.h, src/smf/gsm-sm.c, src/smf/n4-handler.c
If a UPS de-associates and re-associates PFCP it eventually gets out of sync with the CPS with respect to SEID values. This is because the UPS will generate new SEID values each time (i.e. after Session-Set-Delete and Session-Establishment) and returns them in the Session-Establishment-Response, but if session is already established, the CPS will ignore these values.
=> update UPS SEIDs after PFCP re-association

src/sgwu/context.c, src/sgwu/context.h, src/sgwu/init.c, src/upf/context.c, src/upf/context.h, src/upf/init.c
Major PR adds the following stats functions to the UPS (upf and sgwu):
- apn: (UPF only, blank if not assigned)
- ip4: (UPF only, blank if not assigned)
- ip6: (UPF only, blank if not assigned)
- seid_cp:  the SEID used by the control plane to manage tunnels (i.e. from sgwc-sgwu and from smf-upf)
- seid_up: the SEID used by forwarding tunnels in the data-plane (i.e. eNB-sgwu-upf-Internet)
=> add stats reporting to ups

README.md, lib/app/ogs-context.c, lib/pfcp/context.c, lib/proto/types.h, src/amf/context.h, src/mme/mme-context.c, src/mme/mme-context.h, tests/common/context.h
each KeyLTE edge-router gets its own served TAI so we obviously need more than 16. 256 seems good for now but we might go even higher in the future.
=> increase OGS_MAX_NUM_OF_SERVED_TAI from 16 to 256

README.md, lib/pfcp/context.c, lib/pfcp/context.h, lib/pfcp/path.h
This adds a send_asr option to remote PFCP configuraiton. Default value (and previous behavior) is set to "true" but when set to "false", this side will NOT send PFCP association requests to the remote side. It will still listen to and respond to PFCP requests but they must be initiated from the remote side.
This is important for our architecture because we define a large number of UPS entities (sgwu and upf) by TAC, and as such the CPS must have corresponding entries in e.g. sgwc.yaml. But when these entities are offline, our CPS logs become filled up with failed association requests sent from the CPS to the UPSes. With CPS side setting this option to "false" the CPS stays silent and all online UPSes initiate PFCP sessions.
=> add send_asr PFCP option

src/mme/esm-handler.c, src/mme/mme-context.c, src/mme/mme-context.h, src/mme/mme-init.c, src/mme/s1ap-handler.c, src/sgwc/context.c, src/sgwc/context.h, src/sgwc/init.c, src/smf/context.c, src/smf/context.h, src/smf/init.c, src/smf/s5c-handler.c
Instead of maintaining separate functions for adding and removing, consolidated all stats reporting code into a single function that can be called idempotently since all it does is write out current values. This also greatly simplifies the difference between us and upstream. Already had written this code for the UPS, now just applying the same architectural design to CPS.
=> Re-architect stats collection for CPS

lib/pfcp/xact.c
The if (ogs_pfcp_sendto(xact->node, pkbuf) != OGS_OK) line will executed if the sending node encounters any sort of socket/sendto errors. In this case, jumping to out and calling pfcp_xact_delete() without any new timers set will essentially "deadlock" this side of the connection into radio silence. If we just log the error and return, the error is picked up and handled by the calling function, the next timer gets set, and code proceeds as normal.
Socket errors are uncommon over localhost but this problem is actually big for our deployment context because our routers will often hit very temporary/intermittent socket errors if the VPN they're using to communicate stumbles or isn't yet online.
=> [pfcp] response_timeout should never call ogs_pfcp_xact_delete

src/sgwc/init.c, src/sgwc/pfcp-sm.c, src/sgwc/sgwc-sm.h, src/sgwu/init.c, src/sgwu/pfcp-sm.c, src/sgwu/sgwu-sm.h, src/smf/init.c, src/smf/pfcp-sm.c, src/smf/smf-sm.h, src/upf/init.c, src/upf/pfcp-sm.c, src/upf/upf-sm.h
This PR adds pfcp node association information (who's associated, their IP address, and TAC if exists) to smf, upf, sgwc, and sgwu.
=> add PFCP information to /tmp/open5gs

src/sgwc/context.c, src/smf/context.c
Adding SEID information (local and remote) to /tmp/open5gs for CPS. This will help debug any further sync issues that occur.
=> add SEID information to CPS printouts

src/mme/mme-context.c, src/sgwc/context.c, src/sgwc/sxa-handler.c, src/sgwu/context.c, src/smf/context.c, src/smf/n4-handler.c, src/upf/context.c
Adding a bunch more /tmp variables to help debug (1) the session IDs in-between CPS/UPS and (2) some more details about what exact state the UPS has.
=> printout ups variables

src/smf/gsm-sm.c
we have observed some cases where the smf receives a CreateSessionRequest (from sgwc) for a preexisting session. Currently (when in state operational) the smf just silently drops this message, which in turn blocks the rest of the registration procedure. Preferred idempotent behavior would be to handle the CSR message by removing any active sessions and proceeding as if it were a new request.
=> handle CreateSessionRequest even when in state operational

lib/pfcp/context.c, lib/pfcp/context.h, src/sgwc/context.c, src/sgwc/pfcp-sm.c, src/sgwc/s5c-handler.c, src/sgwc/sxa-handler.c, src/sgwu/context.c, src/sgwu/sxa-handler.c, src/smf/context.c, src/upf/context.c, src/upf/n4-handler.c
This is a medium-large size improvement to the stats information currently printed in /tmp/open5gs/*/list_sessions. It now correctly prints out the seid information (CP and UP) as well as the teids (used for data-plane GTP tunneling), and links PDRs to FARs in the UPS components.
=> print full tunnel information in /tmp/open5gs

configs/open5gs/amf.yaml.in, configs/open5gs/ausf.yaml.in, configs/open5gs/bsf.yaml.in, configs/open5gs/mme.yaml.in, configs/open5gs/nrf.yaml.in, configs/open5gs/nssf.yaml.in, configs/open5gs/pcf.yaml.in, configs/open5gs/sgwc.yaml.in, configs/open5gs/sgwu.yaml.in, configs/open5gs/smf.yaml.in, configs/open5gs/udm.yaml.in, configs/open5gs/udr.yaml.in, configs/open5gs/upf.yaml.in, lib/app/ogs-context.c, lib/app/ogs-context.h, src/sgwc/pfcp-path.c, src/smf/gsm-sm.c
Right now the timeout/retransmit values for almost all messages (GTP, PFCP, SBI, Diameter) are set to message.duration (default value 10sec). Having all these timers set to the same value can create weird race-conditions when something times out; to this point the 3GPP specifically recommends fine-tuning these parameters to appropriate values. For example, mme->sgwc GTPv2 messages should naturally have a longer timeout than sgwc->smf GTPv2 messages or sgwc->sgwu PFCP messages. This PR addresses this limitation by breaking up message.duration into sub-parameters (gtp_duration, sbi_duration, pfcp_duration), each of which is individually configurable.
=> allow fine-grained setting of message timers

lib/core/ogs-timer.c, lib/core/ogs-timer.h
We recently fixed a timer leak issue that was incredibly hard to understand, in no small part because it's currently possible to re-assign or double-free timers and mess with the values of unassigned items in the pool. The doublefree is now caught, but setting/clearing an "assigned" bit will protect the timer pool and allow us to quickly identify and debug these issues in the future.
=> add sanity checks to ogs_timer alloc/free

src/smf/gsm-sm.c
I incorrectly assumed that ogs_timer_delete() was idempotent, but it is not! As such we need to set the pointer to NULL and put our own subsequent checks in to ensure that every timer pointer gets freed once and only once.
=> fix double-free of diameter ogs_timer

src/sgwc/pfcp-path.c, src/sgwc/sxa-handler.c, src/smf/context.h, src/smf/gsm-sm.c, src/smf/pfcp-path.c
Right now, when PFCP reassociates a CPS (sgwc or smf) with UPS (sgwu or upf), the CPS re-sends a CSR for all PFCP sessions it has associated with the UPS, including any sessions that were in the middle of being established or torn down. This is a simple fix to ensure that it only re-sends requests for any active (already fully established) sessions.
=> only resend established pfcp sessions on reassociation

src/sgwc/pfcp-path.c, src/smf/gsm-sm.c, src/smf/s5c-handler.c
Right now almost all failures get coded as "OGS_GTP2_CAUSE_REMOTE_PEER_NOT_RESPONDING." If we code different failures as different GTP error messages, it makes it easier to glean a bit of information from the failure from a quick glance at the logs.
=> more articulate/unique GTP error messages

src/smf/context.h, src/smf/gsm-sm.c, src/smf/pfcp-path.c
When a PFCP timer fires, it needs to have access to the old xact that was expired in order to lookup the type, associated GTP xact, and send the correct GTP error message.
=> [pfcp] timer needs a pointer to pfcp_xact

src/sgwc/context.c, src/sgwc/context.h, src/sgwc/s11-handler.c, src/sgwc/s5c-handler.c, src/sgwc/sxa-handler.c, src/smf/context.c, src/smf/context.h, src/smf/gn-handler.c, src/smf/gsm-sm.c, src/smf/n4-handler.c, src/smf/pfcp-sm.c, src/smf/s5c-handler.c, src/smf/smf-sm.c
sgwc_sess_t and smf_sess_t pointers are stored for a message, and run the risk of being stale/freed by the time a response is received or timeout occurs. we use an "active" bit to indicate if the session is still valid or was previously cleared by {sgwc|smf}_sess_remove.
=> [sgwc][smf] check if session is active before dereferencing

src/sgwc/context.c, src/sgwc/s11-handler.c, src/smf/context.c, src/smf/gn-handler.c, src/smf/npcf-handler.c, src/smf/s5c-handler.c
As currently written, if the no_pfcp_rr_select option is set to true and there are no suitable SGWC or UPF for a given UE, the code will simply return the first UPS node regardless of whether it's even attached or not, which could cause some obscure issues later. Correct/expected behavior in this context is to reject the UE.
=> [smf][sgwc] fix upf/sgwc assignment when no_pfcp_rr_select: true

src/sgwc/s5c-handler.c, src/sgwc/sxa-handler.c
A couple of sgwc assertions sometimes fail if a message has timed-out while waiting for a response. Instead of asserting/panicking we should check context and handle gracefully (logging an error, cleaning up context, and returning).
=> [sgwc] minor transaction context error-handling

src/mme/mme-s11-handler.c, src/mme/nas-path.c
Similar fixes as the prior commit to sgwc and smf. Key contributions are (1) not segfaulting out on failed assert()s and (2) proper error-handling (tearing down sessions, error messages when appropriate, etc).
=> [mme] turn various asserts into checks with error-handling

lib/core/ogs-fsm.c
As currently written, state-machine code allows only one state-transition (e.g. from x_state_initial -> x_state_operational) per event. If code at the destination state itself triggers a state transition (e.g. x_state_initial -> x_state_operational -> x_state_exception), the state will be reflected in subsequent calls, but the entry/exit events (e.g. OGS_FSM_EXIT_SIG at x_state_operational and OGS_FSM_ENTRY_SIG x_state_exception) will never get called.
Fix is straightforward; just change a one-off if() check into a while() loop that runs as long as the new state is not the same as the old state.
=> [core] allow for multiple FSM state transitions

src/mme/mme-s11-handler.c, src/sgwc/s11-handler.c, src/sgwc/s5c-handler.c, src/smf/s5c-handler.c
For full 3GPP compliance, message sanity checks need to be performed in a certain order. For example, the sender's TEID must be sanity-checked very early so that (a) we error out (with TEID=0) if it is invalid or (b) the error-messages generated from any subsequent sanity-checks have the correct TEID value filled in.
=> [mme][sgwc][smf] reorder sanity-checking

src/sgwc/s11-handler.c
Right now, if the sgwc sends an s5c message to the pgw and it does not get a response, gtp_sess_timeout() simply logs an error-message. With this fix, the sgwc also sends a GTP error message (with cause OGS_GTP2_CAUSE_PGW_NOT_RESPONDING) back to the mme. It also expands gtp_sess_timeout() to cover Create Session Requests as well as GTP Delete Session Requests.
=> [sgwc] send s11 error to mme on s5c timeout

src/sgwc/sxa-handler.c
This codepath occurs when the sgwc sends a delete_session_request message to the sgwu and receives a delete_session_response indicating failure. Currently, the sgwc simply logs an error and sends a gtp error message back to the mme, and essentially leaves the sgwc session context intact. I believe the correct behavior in this context is to also delete/remove the sgwc session. Note that the PFCP delete_session operation is idempotent (i.e. the sgwu will return a successful response even if the session does not exist) so this context should occur quite infrequently.
=> [sgwc] teardown sess if delete_session_request not accepted

src/smf/context.h, src/smf/gsm-sm.c, src/smf/smf-sm.h
The smf constructs a state-machine for each session, mostly contained in src/smf/gsm-sm.c. I was fixing a bug and noticed that there are a lot of "leaks" where the state machine can get hung-up or doesn't error-out properly (i.e. the code does not send GTP/Diameter error messages or teardown state). Some (but not all) of these conditions are even noted with "FIXME" comments. Additionally, there are several places (usually during a state machine transition) where code is duplicated.
To fix these issues, I added a key state, smf_gsm_state_teardown(), which can be transitioned to from any other state. This state effectively (1) figures out what protocol teardown needs to happen, (2) transitions through these states as needed, and then (3) transitions out to …
=> [smf] state machine improvements

tests/registration/meson.build
I've noticed that sometimes (it is unclear exactly why/when) the Ubuntu testing suite fails with a TIMEOUT on the registration test. This has been a hard problem to understand/debug because my home environments are naturally different than GitHub's testing suite environment, but I've noticed anecdotally that even under the best conditions at home, the registration test takes 22sec, which is substantially longer than any of the other tests.
I suspect that the GitHub CI environment does not make hard guarantees about the resources allocated for testing, and as a result we will sometimes see TIMEOUT failures when insufficient compute resources are provisioned for the test. I am increasing the TIMEOUT value from the default (30sec) to 45sec for the registration test only, on the hunch that …
=> [tests] increase registration timeout to 45sec

.github/workflows/meson-ci.yml
For some still-unknown reason the GitHub CI tests sometimes/sporadically fail with GitHub hosted runners. My hunch is that this has to do with constrained/non-guaranteed virtual resources. Self-hosting on our own digital ocean droplet appears to have resolved this issue.
=> [tests] change github runner to self-hosted

lib/pfcp/path.c
sendto() was crashing the entire SMF when it received an EDESTADDRREQ error. True source of the error is unknown (maybe wireguard hiccupping? looks like the packet was sent out on the wrong wg tunnel) but regardless of the error we should actually just handle gracefully, log error, and move on. PFCP already has its own retrans/recovery mechanisms so loss here is irrelevant.
=> [pfcp] sendto should always return OGS_OK

lib/pfcp/context.h, src/sgwc/pfcp-sm.c, src/smf/pfcp-sm.c
The already_associated variable was used to reduce chatter, in that the first time the CPS associates with a UPS, it will not ask it to delete all sessions. HOWEVER this did not take into account the situation wherein the CPS crashes and re-associates with a UPS, in which case the CPS thinks it's the first association but the UPS still has some "ghost" sessions that can linger and cause signaling issues. Thus we need to always send the reset message when we join just to make sure we're working with a clean slate.
=> remove already_associated variable

lib/ipfw/expand_number.c, lib/ipfw/humanize_number.c, lib/ipfw/missing.h
<sys/cdefs.h> is not included with musl, which we use to compile for smaller embedded architectures. More importantly, its use is also deprecated and should be removed regardless. Additionally, best I can tell, cdefs.h is included in these three files but never used, and compilation succeeds just fine without it.
=> removing cdefs.h so we can compile with musl

src/sgwc/s5c-handler.c
Tiny logic bug-fix. This conditional returns if s11_xact is null. However, it is always null at this point since it's dereferenced from s5c_xact below.
=> [sgwc] s11_xact checked unnecessarily

src/mme/mme-s11-handler.c
Somewhat convoluted bug with a simple fix. When MME receives a DownlinkDataNotification indicating an error and the UE is in state Connected, it (1) sends a UEContextRelease to teardown the existing S1AP sessions and then (2) sends a Paging message to the relevant enb to induce reconnection. We need to store Paging info in this function, before sending the ContextRelease, because otherwise we don't know the right bearer. If Paging info is not stored and the eNB never responds, we eventually get a crash emm-sm.c:140 because we cannot access the paging info.
=> [mme] store paging info during context release

tests/app/5gc-init.c
The open5gs testing framework uses a hard-coded wait time before running tests to ensure all components are up and talking to each other. The 5gc value is 500ms but needs to be longer so that Diameter connections come up; 5sec appears to solve this problem consistently.
=> increase 5gc test startup time

misc/db/open5gs-dbctl
MongoDB updated itself and broke compatibility with open5gs-dbctl script. Pulling these fixes from upstream open5gs to get stable/compatibility back.
=> bump open5gs-dbctl v2.6.0

misc/db/open5gs-dbctl
MongoDB has updated itself and as a result broke compatibility with the open5gs-dbctl script. Fix was already in upstream open5gs but we need to pull now to keep compatibility with Mongo.
=> bump open5gs-dbctl

misc/db/open5gs-dbctl
As written the open5gs-dbctl update_apn feature only supports dynamic IP addressing, and also had a bug. This feature (a) fixes that bug and (b) provides support for an optional IPv4 address. Syntax keys on the number of arguments, similar to open5gs-dbctl add. Note that the default slice_num is usually 0.
=> [open5gs-dbctl] command-line feature to add an apn

src/amf/gmm-handler.c
If the 5G UE asks for a DNN (5g's version of an APN) that we don't support, the amf rejects it with a "DNN Not Supported OR Not Subscribed in the Slice" log message. This is accurate but kinda cryptic. I expanded the error message to indicate the name of the APN the UE is requesting, makes the message more intuitive and helps us debug.
=> make reject due to DNN mismatch clearer in logs
